version: '3.0'
services:
  nginx:
    container_name: nginx-build
    build: ./nginx
    ports:
      - "80:80"
    restart: always
    # volumes:
    #   - ./app:/app
    depends_on:
      - fastapi
  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi-build
    command: gunicorn -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:8000
    restart: always
    volumes:
      - ./app:/app
    expose:
      - "8000"
